apiVersion: v1
kind: Pod
metadata:
  name: node-api-pod
spec:
  containers:
    - image: node-api
      name: node-api
      imagePullPolicy: Never
      resources: {}
      ports:
        - containerPort: 3000